import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppWindow, Settings, Bug, House } from "lucide-react";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="navigation">
          <Link href="/" aria-label="Home">
            <House />
          </Link>
          <Link href="/" aria-label="Settings">
            <Settings />
          </Link>
          <Link href="/" aria-label="Overview">
            <AppWindow />
          </Link>
          <Link href="/#errors" aria-label="Errors">
            <Bug />
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
