import * as stylex from "@stylexjs/stylex";
import { colors } from "@/src/styles/tokens/index.stylex";
export const nav = stylex.create({
  navigation: {
    paddingTop: "15px",
    width: "50px",
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "16px",
    backgroundColor: "var(--card)",
    position: "fixed",
    left: 0,
    top: 0,
    overflow: "hidden",
  },
  navigation1: {
    borderRightWidth: "1px",
    borderRightColor: colors.accent,
    borderRightStyle: "solid",
  },
  navigation2: {
    borderRightWidth: "1px",
    borderRightColor: colors.accent2,
    borderRightStyle: "solid",
  },
  navigation3: {
    borderRightWidth: "1px",
    borderRightColor: colors.accent3,
    borderRightStyle: "solid",
  },
  navigation4: {
    borderRightWidth: "1px",
    borderRightColor: colors.accent4,
    borderRightStyle: "solid",
  },
  link: {
    padding: "8px",
    width: "100%",
    display: "flex",
    justifyContent: "center",
  },
  websitesActive: {
    backgroundColor: colors.accent3,
    position: "relative",
    borderTopLeftRadius: "20px",
    borderBottomLeftRadius: "20px",
    ":before": {
      content: '""',
      position: "absolute",
      right: 0,
      top: 0,
      width: "20px",
      height: "20px",
      transform: "translateY(-20px)",
      borderBottomRightRadius: "20px",
      boxShadow: `4px 4px 0 4px ${colors.accent3}`,
    },
    ":after": {
      content: '""',
      position: "absolute",
      right: 0,
      bottom: 0,
      width: "20px",
      height: "20px",
      transform: "translateY(+20px)",
      borderTopRightRadius: "20px",
      boxShadow: `4px -4px 0 4px ${colors.accent3}`,
    },
  },
  bugsActive: {
    backgroundColor: colors.accent4,
    position: "relative",
    borderTopLeftRadius: "20px",
    borderBottomLeftRadius: "20px",
    ":before": {
      content: '""',
      position: "absolute",
      right: 0,
      top: 0,
      width: "20px",
      height: "20px",
      transform: "translateY(-20px)",
      borderBottomRightRadius: "20px",
      boxShadow: `4px 4px 0 4px ${colors.accent4}`,
    },
    ":after": {
      content: '""',
      position: "absolute",
      right: 0,
      bottom: 0,
      width: "20px",
      height: "20px",
      transform: "translateY(+20px)",
      borderTopRightRadius: "20px",
      boxShadow: `4px -4px 0 4px ${colors.accent4}`,
    },
  },
  componentsActive: {
    backgroundColor: colors.accent2,
    position: "relative",
    borderTopLeftRadius: "20px",
    borderBottomLeftRadius: "20px",
    ":before": {
      content: '""',
      position: "absolute",
      right: 0,
      top: 0,
      width: "20px",
      height: "20px",
      transform: "translateY(-20px)",
      borderBottomRightRadius: "20px",
      boxShadow: `4px 4px 0 4px ${colors.accent2}`,
    },
    ":after": {
      content: '""',
      position: "absolute",
      right: 0,
      bottom: 0,
      width: "20px",
      height: "20px",
      transform: "translateY(+20px)",
      borderTopRightRadius: "20px",
      boxShadow: `4px -4px 0 4px ${colors.accent2}`,
    },
  },
  homeActive: {
    backgroundColor: colors.accent,
    position: "relative",
    borderTopLeftRadius: "20px",
    borderBottomLeftRadius: "20px",
    ":before": {
      content: '""',
      position: "absolute",
      right: 0,
      top: 0,
      width: "20px",
      height: "20px",
      transform: "translateY(-20px)",
      borderBottomRightRadius: "20px",
      boxShadow: `4px 4px 0 4px ${colors.accent}`,
    },
    ":after": {
      content: '""',
      position: "absolute",
      right: 0,
      bottom: 0,
      width: "20px",
      height: "20px",
      transform: "translateY(+20px)",
      borderTopRightRadius: "20px",
      boxShadow: `4px -4px 0 4px ${colors.accent}`,
    },
  },
});
